### ISSUE TITLE
opensuse leap 15.0 repo doesn't exist

### ISSUE THREAD

**Issue by hemna** [openSUSE/vagrant-ceph#46]
The config.yml that describes the box config for Leap 15.0 points to a non existent repo.

https://github.com/openSUSE/vagrant-ceph/blob/master/config.yml#L96

**Comment by denisok** [comment]
@hemna correct. We don't support 15.0, we might just need to remove it from the config,

**Comment by toabctl** [comment]
This seems to be solved. Can be closed imo
